add some options

diff --git a/bin/anyenv-update b/bin/anyenv-update
--- a/bin/anyenv-update
+++ b/bin/anyenv-update
@@ -1,19 +1,117 @@
 #!/usr/bin/env bash
+#
 # Summary: Update all **env and all installed plugins.
 #
-# Usage: anyenv update
+# Usage: anyenv update [--force] [--verbose|--quiet|--noop] [--without-plugin] [<envs>]
+#
+#  -f/--force       Force update
+#  -v/--verbose     Verbose mode: print downloading status to stdout
+#  -q/--quiet       Quiet mode: no printing
+#  -n/--noop        Noop mode: dry run and do nothing
+#  --without-plugin Update envs, but not update plugin of each envs
+#
+# For detailed information, see: https://github.com/znz/anyenv-update
+#
 
-set -euo pipefail
-[ -n "${ANYENV_DEBUG-}" ] && set -x
+set -e
+[ -n "$ANYENV_DEBUG" ] && set -x
+
+# Provide anyenv completions
+if [ "$1" = "--complete" ]; then
+  echo --force
+  echo --verbose
+  echo --quiet
+  echo --noop
+  echo --without-plugin
+  echo anyenv
+  exec anyenv-envs
+fi
+
+usage () {
+  anyenv-help update 2>/dev/null
+  [ -z "$1" ] || exit "$1"
+}
+
+parse_options () {
+  OPTIONS=()
+  ARGUMENTS=()
+  local arg option index
+
+  for arg in "$@"; do
+    if [ "${arg:0:1}" = "-" ]; then
+      if [ "${arg:1:1}" = "-" ]; then
+        OPTIONS[${#OPTIONS[*]}]="${arg:2}"
+      else
+        index=1
+        while option="${arg:$index:1}"; do
+          [ -n "$option" ] || break
+          OPTIONS[${#OPTIONS[*]}]="$option"
+          index=$(($index+1))
+        done
+      fi
+    else
+      ARGUMENTS[${#ARGUMENTS[*]}]="$arg"
+    fi
+  done
+}
+
+indent_output() {
+  while read -r data; do
+    printf " ${color}|${reset}  %s\n" "$data"
+  done
+}
+
+print_colored() {
+  if [ -z "$QUIET" ]; then
+    printf "${color}%s${reset}\n" "$1"
+  fi
+}
+
+get_allenvs () {
+  echo 'anyenv' $(anyenv-envs)
+}
+
+git_currentbranch () {
+  command git branch | grep '*' | awk '{print $2}'
+}
+
+git () {
+  if [ -n "$NOOP" ]; then
+    # dry run
+    echo git "$@" | indent_output
+    return ${PIPESTATUS[0]}
+  elif [ -n "$QUIET" ]; then
+    # mute all
+    command git "$@" &>/dev/null
+  elif [ -n "$VERBOSE" ]; then
+    # output all
+    command git "$@" 2>&1 | indent_output
+    return ${PIPESTATUS[0]}
+  else
+    # output only stderr
+    command git "$@" 2>&1 >/dev/null | indent_output
+    return ${PIPESTATUS[0]}
+  fi
+}
+
+print_use_forceopt () {
+  if [ -z "$QUIET" ]; then
+    printf ' \e[1;33m|  Failed to update. Use `verbose` option for detailed, or `force` option.\e[0m\n'
+  fi
+}
 
 anyenv_update () {
   if [ -d .git ]; then
-    echo "Updating '$1'..."
-    git pull
+    print_colored "Updating '$1'..."
+    if [ -n "$FORCE" ]; then
+      git fetch --prune
+      git reset --hard "origin/$(git_currentbranch)"
+    else
+      git pull --no-rebase --ff || print_use_forceopt
+    fi
   else
-    echo "Skipping '$1'"
+    print_colored "Skipping '$1'; not git repo"
   fi
-  echo
 }
 
 anyenv_update_plugins () {
@@ -26,13 +124,67 @@ anyenv_update_plugins () {
   shopt -u nullglob
 }
 
-cd "${ANYENV_ROOT:-$(anyenv root)}"
-anyenv_update anyenv
-anyenv_update_plugins
+# Parse command line flags
+FORCE=""
+VERBOSE=""
+QUIET=""
+NOOP=""
+WITHOUT_PLUGIN=""
 
-for env in $(anyenv envs); do
+parse_options "$@"
+for option in "${OPTIONS[@]}"; do
+  case "$option" in
+  "h" | "help" )
+    usage 0
+    ;;
+  "f" | "force" )
+    FORCE=true
+    ;;
+  "v" | "verbose" )
+    VERBOSE=true
+    ;;
+  "q" | "quiet" )
+    QUIET=true
+    ;;
+  "n" | "noop" )
+    NOOP=true
+    ;;
+  "without-plugin" )
+    WITHOUT_PLUGIN=true
+    ;;
+  * )
+    echo "no such option: ${option}" >&2
+    echo
+    usage 1 >&2
+    ;;
+  esac
+done
+
+# Set colored output for TTY
+if [ -t 1 ]; then
+  color="\e[1;32m"
+  reset="\e[0m"
+else
+  color=""
+  reset=""
+fi
+
+if [ -n "$NOOP" ] && [ -n "$QUIET" ]; then
+  QUIET=""
+  print_colored "Both --noop and --quiet given; ignoring --quiet" >&2
+fi
+
+TARGET_ENVS="${ARGUMENTS[@]}"
+if [ "${#ARGUMENTS[@]}" -eq 0 ]; then
+  # set all envs when no args are given
+  TARGET_ENVS=$(get_allenvs)
+fi
+
+for env in $TARGET_ENVS; do
   ENV_ROOT_VALUE=$(echo "${env}_ROOT" | tr '[:lower:]' '[:upper:]')
-  eval cd "\${${ENV_ROOT_VALUE}:-\$($env root)}"
+  ENV_ROOT_VALUE=$(eval echo "\${${ENV_ROOT_VALUE}:-\$($env root)}")
+  
+  cd $ENV_ROOT_VALUE
   anyenv_update "$env"
-  anyenv_update_plugins
+  [ -n "$WITHOUT_PLUGIN" ] || anyenv_update_plugins "$env"
 done
